name: tic_tac_toe
description: A Tic Tac Toe game

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^5.0.0

  cupertino_icons: ^1.0.2
  
  font_awesome_flutter: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

